apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:v1
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: api-secrets
            - configMapRef:
                name: api-cfgmaps
---
apiVersion: v1
kind: Service
metadata:
  name: api-np
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
